language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
notifications:
  email: false
node_js:
  - 10.18
  - 12
  - 14
  - 15
before_install:
  - nvm install-latest-npm
install: npm install
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
